name: analyzer_kit
description: A Dart Analyzer plugin providing lint rules and quick fixes for analyzer_kit annotations.
version: 1.0.0+2
homepage: https://github.com/maranix/analyzer_kit/tree/main/packages/analyzer_kit
repository: https://github.com/maranix/analyzer_kit/tree/main/packages/analyzer_kit
issues: https://github.com/maranix/analyzer_kit/issues

topics:
  - analyzer
  - linting
  - codegen
  - annotation

environment:
  sdk: ^3.10.4

resolution: workspace

plugins:
  platforms:
    dart:
      pluginClass: AnalyzerKit
      fileName: main.dart

dependencies:
  analysis_server_plugin: ^0.3.10
  analyzer: ^10.2.0
  analyzer_plugin: ^0.14.4
  code_builder: ^4.11.0
  dart_style: ^3.1.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  analyzer_testing: ^0.2.1
