include: package:lints/recommended.yaml

plugins:
  dart_analyzer_kit:
    path: packages/dart_analyzer_kit

    diagnostics:
      unused_copy_with_annotation: true
      unused_serialize_annotation: true
      unused_debug_string_annotation: true
      unused_override_equality_annotation: true
